//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licenta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dosar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dosar()
        {
            this.DUs = new HashSet<DU>();
        }
    
        public int Id { get; set; }
        public string NumePart1 { get; set; }
        public string NumePart2 { get; set; }
        public Nullable<int> IdTribunal { get; set; }
        public Nullable<System.DateTime> DataDosar { get; set; }
        public string Stadiu { get; set; }
        public string Obiect { get; set; }
        public string Complet { get; set; }
        public Nullable<System.DateTime> Actualizare { get; set; }
        public Nullable<System.DateTime> DataUrmatoareSedinta { get; set; }
        public string TipSolutie { get; set; }
        public Nullable<int> Companie { get; set; }
        public Nullable<int> OrasId { get; set; }
        public string NumarDosar { get; set; }
    
        public virtual City City { get; set; }
        public virtual Company Company { get; set; }
        public virtual TribunalD TribunalD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DU> DUs { get; set; }
    }
}
